---
- name: Ensure Flatpak Installed
  become: true
  ansible.builtin.apt:
    name: flatpak
    state: present

- name: Add the flathub flatpak repository remote to the system installation
  become: true
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
