---
- name: Ensure CLI Utils Installed
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - acl   # required for temp permissions
    - bash-completion
    - calendar
    - cryptsetup
    - curl
    - fd-find
    - htop
    - ncal
    - nmap
    - parted
    - psensor
    - sdparm
    - stow
    - tree
    - vim
    - wireshark

    # - fzf
    # - tldr
    # - xclip         # X11
    # - wl-clipboard  # wayland
