---
- name: Ensure VS Code Installed
  become: true
  ansible.builtin.apt:
    deb: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
    state: present
    autoclean: true

# - name: Install VCSE
#   ansible.builtin.shell: "pnpm install --global @vscode/vsce"
#   args:
#     executable: /bin/bash
#   changed_when: "'added 1 package' in pnpm.stdout"
