---
- name: Common tasks
  hosts:
    - all

  pre_tasks:
    - name: Update APT
      become: true
      ansible.builtin.import_role:
        name: a2k42.misc.update

  roles:
    - a2k42.misc.debug
    - a2k42.security.firewall
    - a2k42.security.clamav
    - a2k42.system.bundle
    - a2k42.system.backports
    - a2k42.developer.bundle

- name: Configure Servers
  hosts: vservers
  roles:
    - a2k42.system.device

- name: Configure Desktop
  hosts: vdesktops
  roles:
    - a2k42.desktop.bundle
    - a2k42.leisure.games
    - a2k42.leisure.modelling
    - a2k42.leisure.music

- name: Configure Laptop
  hosts: laptop
  roles:
    - a2k42.desktop.bundle
    - a2k42.misc.debug

- name: Configure Desktop
  hosts: desktop
  roles:
    - a2k42.developer.texlive
