---
- name: Install Blender Packages
  become: true
  become_user: "{{ modelling_user_name }}"
  community.general.flatpak:
    name: "{{ item.name }}"
    state: present
    method: user
  loop:
    - name: org.blender.Blender
