---
- name: Create User
  become: true
  ansible.builtin.user:
    name: "{{ leisure_user }}"
    comment: User
    password: "{{ leisure_password }}"
    update_password: "on_create"
    groups: users,audio,dip,video,plugdev,users,netdev,bluetooth
    # append: true
    shell: /bin/bash
    state: present

- name: Add the flathub flatpak repository remote to the user installation
  become: true
  become_user: "{{ leisure_user }}"
  community.general.flatpak_remote:
    name: flathub
    state: present
    method: user
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
# flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

- name: Install Flatpak Packages
  become: true
  become_user: "{{ leisure_user }}"
  community.general.flatpak:
    name: "{{ item.name }}"
    state: present
    method: user
  loop:
    - name: org.kde.ktorrent
    - name: com.valvesoftware.Steam

- name: Install Flatpak Packages
  become: true
  community.general.flatpak:
    name: "{{ item.name }}"
    state: present
    method: system
  loop:
    - name: com.spotify.Client
