---
- name: Reboot
  become: true
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible for kernel update"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
