# moutpoints must be unique as they are made into systemd `.mount` files
---
- name: Ensure mountpoints exist for crypttab
  become: true
  ansible.builtin.file:
    path: "/mnt/{{ item.name | trim }}"
    state: directory
    mode: "0755"
  loop: "{{ device_ }}"

- name: Setup crypttab
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/crypttab
    regexp: "^{{ item.name | trim }}"
    line: "{{ item.name }} LABEL={{ item.name }}      /etc/cryptsetup-keys.d/crypt-{{ item.name | trim }}.key {{ device_crypt_options }}"
    backup: true
    state: present
    create: true
    mode: "0644"
  loop: "{{ device_ }}"

# https://www.freedesktop.org/software/systemd/man/systemd.mount.html
- name: Setup fstab for crypttab
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/fstab
    regexp: "^/dev/mapper/{{ item.name | trim }}"
    line: "/dev/mapper/{{ item.name }} /mnt/{{ item.name }} {{ item.fs }} {{ device_fstab_options }}  0  0"
    backup: true
    state: present
  loop: "{{ device_ }}"

- name: Ensure additional mountpoints exist
  become: true
  ansible.builtin.file:
    path: "/mnt/{{ item | trim }}"
    state: directory
    mode: "0755"
  loop:
    - snapshot
    - usb

- name: Add additional devices to fstab
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/fstab
    regex: "^LABEL=Ventoy"
    line: "^LABEL=Ventoy       /mnt/usb    exfat {{ device_fstab_options }}  0  0"
    backup: true
    state: present

  # archlinux docs suggest nofail option only works with keyfiles, could fail waiting for passphrase in crypttab
  # x-systemd.device-timeout=3 was causing timeout (I can't type passphrase that quick) but didn't on old system (default 90s)
  # use timeout with nofail,auto - here we don't need it
