---
- name: Download Julia
  ansible.builtin.import_tasks: julia_download.yaml
  become: true
  when: not julia_use_juliaup

- name: Run Julia Installer
  ansible.builtin.import_tasks: julia_installer.yaml
  become: false
  when: julia_use_juliaup

- name: Check if Revise.jl Installed
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.julia/packages/Revise"
  register: revise_package
  changed_when: false

- name: Copy Install Script
  ansible.builtin.copy:
    src: install.jl
    dest: "{{ ansible_user_dir }}/.julia/config/"
    mode: "0644"
  # when: not revise_package.stat.exists

- name: Add Revise.jl Package
  ansible.builtin.command: "{{ ansible_user_dir }}/.juliaup/bin/julia --startup-file=no {{ ansible_user_dir }}/.julia/config/install.jl"
  register: result
  when: julia_use_juliaup
  changed_when: not 'No Changes' in result.stderr

- name: Show result
  ansible.builtin.debug:
    msg: "{{ result.stderr }}"

- name: Startup config
  ansible.builtin.copy:
    src: startup.jl
    dest: "{{ ansible_user_dir }}/.julia/config/"
    mode: "0644"

- name: Add Julia Project Alias
  ansible.builtin.lineinfile:
    path: ~/.bash_aliases
    regex: "^alias jp="
    line: "alias jp='julia --project=. --optimize=0'"
    mode: "0644"
    create: true
